name = "HyFlex"
uuid = "91fd1720-3559-46da-9fc7-1cf77dc63782"
authors = ["Johan Van Kerckhoven <johan.vankerckhoven@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
